# Парсинг данных ТОП 250-Фильмов

### Подключение библиотек

In [153]:
from bs4 import BeautifulSoup as bs
import requests
import pandas as pd
import time
import re

### URL ссылка сайта и получение информации

# Загрузка главной страницы

In [154]:
url = 'https://www.kinoafisha.info/rating/movies/imdb/'

headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36'
}

response = requests.get(url, headers=headers, timeout=30)
print(f"Статус: {response.status_code}")

soup = bs(response.text, 'html.parser')

Статус: 200

### Парсинг

In [155]:
movies = soup.find_all('div', class_='movieList_item')
print(f"Всего блоков: {len(movies)}")

result_list = {
    'title': [], 'rating': [], 'year': [], 'country': [], 'description': []
}

for i, movie in enumerate(movies[:250]):
    # Рейтинг
    rating_elem = movie.find('span', class_='movieItem_itemRating')
    rating = rating_elem.get_text(strip=True) if rating_elem else ''
    
    title_elem = movie.find(class_='movieItem_title')
    if not title_elem:
        title = ''
        film_url = ''
    else:
        title = title_elem.get_text(strip=True)
        film_url = title_elem.get('href', '') if title_elem.name == 'a' else ''
    
    # Год и страна
    year_span = movie.find('span', class_='movieItem_year')
    if year_span:
        year_text = year_span.get_text(strip=True)
        parts = year_text.split(',')
        year = parts[0].strip()
        country = parts[1].strip() if len(parts) > 1 else ''
    else:
        year = ''
        country = ''
    
    # Описание
    description = ''
    if film_url:
        if not film_url.startswith('http'):
            film_url = 'https://www.kinoafisha.info' + film_url
        try:
            film_resp = requests.get(film_url, headers=headers, timeout=10)
            if film_resp.status_code == 200:
                film_soup = bs(film_resp.text, 'html.parser')
                desc_div = film_soup.find('div', class_='visualEditorInsertion-info')
                if desc_div:
                    description = desc_div.get_text(strip=True)
                    description = re.sub(r'\s+', ' ', description)
        except:
            pass
    
    result_list['title'].append(title)
    result_list['rating'].append(rating)
    result_list['year'].append(year)
    result_list['country'].append(country)
    result_list['description'].append(description)
    
    print(f"{i+1}. {title} ({year}) - {country}")

print(f"\nСохранено {len(result_list['title'])} фильмов")

df = pd.DataFrame(result_list)

Всего блоков: 250
1. Побег из Шоушенка (1994) - США
2. Крестный отец (1972) - США
3. Темный рыцарь (2008) - США
4. Крестный отец 2 (1974) - США
5. 12 разгневанных мужчин (1957) - США
6. Властелин Колец: Возвращение Короля (2003) - США / Новая Зеландия / Германия
7. Список Шиндлера (1993) - США
8. Властелин Колец: Братство Кольца (2001) - Новая Зеландия / США
9. Криминальное чтиво (1994) - США
10. Хороший, плохой, злой (1966) - Италия / Испания / Германия
11. Властелин Колец: Две крепости (2002) - США / Новая Зеландия / Германия
12. Форрест Гамп (1994) - США
13. Бойцовский клуб (1999) - США / Германия
14. Начало (2010) - США / Великобритания
15. Звездные войны: Эпизод V - Империя наносит ответный удар (1980) - США
16. Матрица (1999) - Австралия / США
17. Славные парни (1990) - США
18. Интерстеллар (2014) - США / Великобритания
19. Пролетая над гнездом кукушки (1975) - США
20. Семь (1995) - США
21. Эта замечательная жизнь (1946) - США
22. Молчание ягнят (1991) - США
23. Семь самураев (1954) - Япония
24. Спасти рядового Райана (1998) - США
25. Зеленая миля (1999) - США
26. Город Бога (2002) - Бразилия / Франция
27. Жизнь прекрасна (1997) - Италия
28. Терминатор 2: Судный день (1991) - США / Франция
29. Звездные войны: Эпизод IV - Новая надежда (1977) - США
30. Назад в будущее (1985) - США
31. Унесенные призраками (2001) - Япония
32. Пианист (2002) - Франция / Германия / Великобритания / Польша
33. Гладиатор (2000) - Великобритания / США
34. Паразиты (2019) - Южная Корея
35. Могила светлячков (1988) - Япония
36. Психо (1960) - США
37. Король Лев (1994) - США
38. Харакири (1962) - Япония
39. Отступники (2006) - США
40. Одержимость (2014) - США
41. Престиж (2006) - США / Великобритания
42. Американская история Х (1998) - США
43. Убить Билла: Кровавое дело целиком (2006) - США
44. Леон (1994) - Франция
45. Человек-Паук: Паутина Вселенных (2022) - Канада / США
46. Новый кинотеатр «Парадизо» (1988) - Франция / Италия
47. Касабланка (1942) - США
48. 1+1 (2011) - Франция
49. Подозрительные лица (1995) - Германия / США
50. Чужой (1979) - США / Великобритания
51. Джанго освобожденный (2012) - США
52. Новые времена (1936) - США
53. Окно во двор (1954) - США
54. Однажды на Диком Западе (1968) - Италия / США
55. Огни большого города (1931) - США
56. Апокалипсис сегодня (1979) - США
57. ВАЛЛ-И (2008) - США
58. Помни (2000) - США
59. Дюна: Часть вторая (2024) - США / Канада
60. Индиана Джонс: В поисках утраченного ковчега (1981) - США
61. Мстители: Война бесконечности (2018) - США
62. Жизнь других (2006) - Германия
63. Человек-паук: Через вселенные (2018) - США
64. Сансет бульвар (1950) - США
65. Свидетель обвинения (1957) - США
66. Тропы славы (1957) - США
67. Сияние (1980) - Великобритания / США
68. Великий диктатор (1940) - США
69. Бесславные ублюдки (2009) - Германия / США
70. 12-я неудача (2023) - Индия
71. Чужие (1986) - США / Великобритания
72. Рай и Ад (1963) - Япония
73. Умница Уилл Хантинг (1997) - США
74. Темный рыцарь: Возрождение легенды (2012) - США / Великобритания
75. Мстители: Финал (2019) - США
76. Тайна Коко (2017) - США
77. Амадей (1984) - США
78. История игрушек (1995) - США
79. Твое имя (2016) - Япония
80. Подводная лодка (1981) - Германия
81. Олдбой (2003) - Южная Корея
82. Храброе сердце (1995) - США
83. Принцесса Мононоке (1997) - Япония
84. Доктор Стрейнджлав, или Как я научился не волноваться и полюбил атомную бомбу (1963) - Великобритания
85. Три идиота (2009) - Индия
86. Красота по-американски (1999) - США
87. Капернаум (2018) - Ливан / Франция
88. Поющие под дождем (1952) - США
89. Джокер (2019) - США
90. Однажды в Америке (1983) - США / Италия
91. Иди и смотри (1985) - СССР
92. Звездные войны: Эпизод VI - Возвращение джедая (1983) - США
93. Реквием по мечте (2000) - США
94. История игрушек: Большой побег (2010) - США
95. Жить (1952) - Япония
96. Охота (2012) - Дания
97. Пожары (2010) - Канада
98. Вечное сияние чистого разума (2004) - США
99. Квартира (1960) - США
100. Лоуренс Аравийский (1962) - Великобритания
101. 2001 год: Космическая одиссея (1968) - США / Великобритания
102. Бешеные псы (1992) - США
103. Схватка (1995) - США
104. Лицо со шрамом (1983) - США
105. Двойная страховка (1944) - США
106. Вверх (2009) - США
107. На север через северо-запад (1959) - США
108. Дети как звезды на Земле (2007) - Индия
109. Цельнометаллическая оболочка (1987) - Великобритания / США
110. М убийца (1931) - Германия
111. Гражданин Кейн (1941) - США
112. Амели (2001) - Франция / Германия
113. Головокружение (1958) - США
114. Развод Надера и Симин (2011) - Иран
115. Крепкий орешек (1988) - США
116. Убить пересмешника (1962) - США
117. Афера (1973) - США
118. Индиана Джонс и последний крестовый Поход (1989) - США
119. Заводной апельсин (1971) - Великобритания
120. Метрополис (1927) - Германия
121. 1917 (2019) - Великобритания / США
122. Большой Куш (2000) - Великобритания / США
123. Секреты Лос-Анджелеса (1997) - США
124. Бункер (2004) - Германия / Италия / Австрия
125. Волк с Уолл-стрит (2013) - США
126. Дангал. Слово борца (2016) - Индия
127. Похитители велосипедов (1948) - Италия
128. Шоу Трумана (1998) - США
129. Оппенгеймер (2023) - США
130. Зеленая книга (2018) - США
131. Остров проклятых (2009) - США
132. Нюрнбергский процесс (1961) - США
133. Бэтмен: начало (2005) - США
134. Гамильтон (2020) - США
135. На несколько долларов больше (1965) - Италия / Испания / Германия
136. Таксист (1976) - США
137. Парк Юрского периода (1993) - США
138. В джазе только девушки (1959) - США
139. Нефть (2007) - США
140. Малыш (1921) - США
141. Отец (2020) - Великобритания / Франция
142. Все о Еве (1950) - США
143. Шестое чувство (1999) - США
144. Ран (1985) - Япония / Франция
145. Казино (1995) - США / Франция
146. Старикам тут не место (2007) - США
147. Нечто (1982) - США
148. Топ Ган: Мэверик (2022) - США
149. Пленницы (2013) - США
150. Убить Билла (2003) - США
151. Лабиринт Фавна (2006) - Мексика / Испания / США
152. Непрощенный (1992) - США
153. Игры разума (2001) - США
154. Сокровища Сьерра Мадре (1948) - США
155. Ходячий замок (2004) - Япония
156. В поисках Немо (2003) - США
157. Клаус (2019) - Испания / Великобритания
158. Телохранитель (1961) - Япония
159. Большой побег (1963) - США
160. Человек-Слон (1980) - США / Великобритания
161. Монти Пайтон и священный Грааль (1975) - Великобритания
162. В случае убийства набирайте "М" (1954) - США
163. The Best of Youth (2003) -
164. Тайна в его глазах (2009) - Испания / Аргентина
165. Унесенные ветром (1939) - США
166. Истребитель демонов: Kimetsu No Yaiba Бесконечная крепость (2025) - Япония
167. Китайский квартал (1974) - США
168. Карты, деньги, два ствола (1998) - Великобритания
169. «V» значит Вендетта (2005) - США / Великобритания / Германия
170. Поймай меня, если сможешь (2002) - США
171. Головоломка (2015) - США
172. Расемон (1950) - Япония
173. Три билборда на границе Эббинга, Миссури (2017) - США / Великобритания
174. На игле (1996) - Великобритания
175. Мост через реку Квай (1957) - Великобритания / США
176. Гарри Поттер и Дары смерти. Часть вторая (2011) - США / Великобритания
177. Возмутительный класс не прошёл экзамен (1975) -
178. Общество мертвых поэтов (1989) - США
179. Дикий робот (2024) - США
180. Воин (2011) - США
181. Фарго (1995) - США
182. Барри Линдон (1975) - Великобритания / США / Ирландия
183. Бешеный бык (1980) - США
184. Бен-Гур (1959) - США
185. Малышка на миллион (2004) - США
186. Безумный Макс: Дорога ярости (2015) - Австралия / США
187. Дети небес (1997) - Иран
188. По соображениям совести (2016) - США
189. Мой сосед Тоторо (1988) - Япония
190. Гран Торино (2008) - США
191. 12 лет рабства (2013) - США / Великобритания
192. Отель "Гранд Будапешт" (2014) - США / Германия
193. Рататуй (2007) - США
194. Перед рассветом (1995) - США / Австрия / Швейцария
195. Воспоминания об убийстве (2003) - Южная Корея
196. Бегущий по лезвию (1982) - США
197. Как приручить дракона (2010) - США
198. Человек-паук: Нет пути домой (2021) - США
199. Исчезнувшая (2014) - США
200. Корпорация Монстров (2001) - США
201. Челюсти (1975) - США
202. Во имя отца (1993) - Ирландия / Великобритания
203. FORD против FERRARI (2019) - США
204. Дикие истории (2014) - Аргентина / Испания
205. Золотая лихорадка (1925) - США
206. Шерлок младший (1924) - США
207. Мэри и Макс (2009) - Австралия
208. Охотник на оленей (1978) - США / Великобритания
209. Плата за страх (1953) - Франция / Италия
210. Паровоз Генерал (1927) - США
211. Логан (2017) - США
212. Рокки (1976) - США
213. Мистер Смит едет в Вашингтон (1939) - США
214. Токийская история (1953) - Япония
215. В порту (1954) - США
216. Пираты Карибского моря: Проклятие черной жемчужины (2003) - США
217. Земляничная поляна (1957) - Швеция
218. В центре внимания (2015) - США
219. Ненависть (1995) - Франция
220. Форма голоса (2016) - Япония
221. Терминатор (1984) - Великобритания / США
222. Третий человек (1949) - Великобритания
223. Махараджа (2024) - Индия
224. Jai Bhim (2021) -
225. Звуки музыки (1965) - США
226. Большой Лебовски (1998) - США / Великобритания
227. Лучшие годы нашей жизни (1946) - США
228. Седьмая печать (1956) - Швеция
229. Комната (2015) - Ирландия / Канада
230. Перед закатом (2004) - США
231. Отель "Руанда" (2004) - США / Великобритания / Италия / ЮАР
232. Суперсемейка (2004) - США
233. Взвод (1986) - США
234. Человек-бензопила. Фильм: История Резе (2025) - Япония
235. Хатико: самый верный друг (2009) - США
236. Изгоняющий дьявола (1973) - США
237. Гонка (2012) - США
238. Волшебник страны Оз (1939) - США
239. Стальной гигант (1999) - США
240. Останься со мной (1986) - США
241. Страсти Жанны Д'Арк (1928) - Франция
242. Мой отец и мой сын (2005) - Турция
243. Битва за Алжир (1966) - Италия / Алжир
244. Служанка (2016) - Южная Корея
245. Телесеть (1976) - США
246. Банды Вассейпура (2012) -
247. Видимость (2015) - Индия
248. Быть или не быть (1942) - США
249. Гроздья гнева (1940) - США
250. Drishyam (2013) -

Сохранено 250 фильмов

In [156]:
df = pd.DataFrame(result_list)

### Вывод таблицы

In [157]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250 entries, 0 to 249
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   title        250 non-null    object
 1   rating       250 non-null    object
 2   year         250 non-null    object
 3   country      250 non-null    object
 4   description  250 non-null    object
dtypes: object(5)
memory usage: 9.9+ KB

In [158]:
df.head(10)

,title,rating,year,country,description
0,Побег из Шоушенка,9.3,1994,США,Успешный банковский служащий Энди Дюфрейн осуж...
1,Крестный отец,9.2,1972,США,В центре культовой криминальной драмы Фрэнсиса...
2,Темный рыцарь,9.1,2008,США,Действие фильма начинается с ограбления Готэмс...
3,Крестный отец 2,9.0,1974,США,Молодой Вито теряет семью из-за преследования ...
4,12 разгневанных мужчин,9.0,1957,США,"Классика кинематографа 1950-х, выросшего из те..."
5,Властелин Колец: Возвращение Короля,9.0,2003,США / Новая Зеландия / Германия,Битва за Средиземье продолжается. Хоббиты и их...
6,Список Шиндлера,9.0,1993,США,"Начало Второй мировой войны. После того, как П..."
7,Властелин Колец: Братство Кольца,8.9,2001,Новая Зеландия / США,"Средиземье — континент, населенный разными и о..."
8,Криминальное чтиво,8.8,1994,США,Джулс Уиннфилд и Винсент Вега – парочка киллер...
9,"Хороший, плохой, злой",8.8,1966,Италия / Испания / Германия,В разгар гражданской войны таинственный стрело...

### Сохранение в csv файл

In [159]:
df.to_csv('top250.csv', index=False, encoding='utf-8-sig')

In [3]:
import pandas as pd

In [4]:
df = pd.read_csv('top250.csv')

In [6]:
df['country'].isna().sum()

np.int64(5)

In [7]:
df['country'].isnull().sum()

np.int64(5)

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   title        500 non-null    object
 1   rating       500 non-null    float64
 2   year         500 non-null    int64
 3   country      495 non-null    object
 4   description  494 non-null    object
dtypes: float64(1), int64(1), object(3)
memory usage: 19.7+ KB

### Парсинг с помощью API к кинопоиску

In [160]:
API_TOKEN = "QKWZN69-DNS4ZWV-HDG2822-RWXZH9Q"
headers = {'X-API-KEY': API_TOKEN, 'Content-Type': 'application/json'}
result_list = {'title': [], 'year': [], 'country': [], 'rating': [], 'description': []}

In [161]:
page = 1
collected = 0
max_attempts = 10
attempts = 0

while collected < 250 and attempts < max_attempts:
    try:
        url = f"https://api.kinopoisk.dev/v1.4/movie?lists=top250&limit=50&page={page}"
        
        response = requests.get(url, headers=headers, timeout=10)
        
        if response.status_code != 200:
            print(f"Ошибка API: статус {response.status_code}")
            attempts += 1
            time.sleep(2)
            continue
            
        data = response.json()
        movies = data.get('docs', [])
        
        for movie in movies:
            if collected >= 250:
                break
            
            # Название
            title = movie.get('name') or movie.get('alternativeName', 'Не указано')
            
            # Год
            year = movie.get('year', 'Не указан')
            
            # Страна
            countries = movie.get('countries', [])
            country = countries[0].get('name', 'Не указана') if countries else 'Не указана'
            
            # Рейтинг
            rating_data = movie.get('rating', {})
            rating = rating_data.get('kp', None)
            if rating:
                rating = str(round(float(rating), 1))
            else:
                rating = 'Нет рейтинга'
            
            # Описание
            description = movie.get('description') or movie.get('shortDescription', 'Описание отсутствует')
            
            result_list['title'].append(title)
            result_list['year'].append(year)
            result_list['country'].append(country)
            result_list['rating'].append(rating)
            result_list['description'].append(description)
            
            collected += 1
            print(f"{collected}. {title[:30]} ({year}) - {country}")
        
        page += 1
        attempts = 0
        time.sleep(0.5)
        
    except requests.exceptions.Timeout:
        print(f"Таймаут на странице {page}, пробуем снова...")
        attempts += 1
        time.sleep(3)
    except requests.exceptions.RequestException as e:
        print(f"Сетевая ошибка: {e}")
        attempts += 1
        time.sleep(3)
    except Exception as e:
        print(f"Неожиданная ошибка: {e}")
        attempts += 1
        time.sleep(2)

print(f"\nСобрано {collected} фильмов из 250")

# Создание DataFrame
df_new = pd.DataFrame(result_list)

1. Батя (2020) - Россия
2. Крик тишины (2019) - Россия
3. Темные воды (2019) - США
4. Уроки фарси (2020) - Россия
5. Подольские курсанты (2020) - Россия
6. Достать ножи (2019) - США
7. Огонь (2020) - Россия
8. Дело Коллини (2019) - Германия
9. Джентльмены (2019) - США
10. Пальма (2020) - Россия
11. Звук свободы (2023) - Мексика
12. Зеленая книга (2018) - США
13. Тайна Коко (2017) - США
14. Гонка (2013) - Великобритания
15. Брестская крепость (2010) - Беларусь
16. Диодорова. Против течения (2024) - Россия
17. Истребитель демонов: Бесконечн (2025) - Япония
18. Боб Тревино поставил лайк (2024) - США
19. Нэчжа побеждает Царя драконов (2025) - Китай
20. Сводишь с ума (2025) - Россия
21. Дикий робот (2024) - США
22. Граф Монте-Кристо (2024) - Франция
23. Нюрнберг. Многомерность зла (2023) - Россия
24. Группа крови (2025) - Россия
25. Как приручить дракона (2025) - США
26. Одна жизнь (2023) - Великобритания
27. Роднина (2025) - Россия
28. Земмельвейс (2023) - Венгрия
29. F1 (2025) - США
30. Оппенгеймер (2023) - США
31. Великолепная поездка (2022) - Франция
32. Дюна: Часть вторая (2024) - США
33. Поток (2024) - Латвия
34. Белая птица: Новое чудо (2023) - США
35. Джокер (2019) - США
36. Однажды в… Голливуде (2019) - США
37. Балканский рубеж (2019) - Россия
38. Опасная игра Слоун (2016) - США
39. Вторая жизнь Уве (2015) - Швеция
40. Омерзительная восьмерка (2015) - США
41. Одержимость (2013) - США
42. Бесславные ублюдки (2009) - Германия
43. Паразиты (2019) - Корея Южная
44. Таксист (2017) - Корея Южная
45. Дангал (2016) - Индия
46. Дело храбрых (2017) - США
47. Невидимый гость (2016) - Испания
48. Отель Мумбаи: Противостояние (2018) - США
49. Твоё имя (2016) - Япония
50. Три билборда на границе Эббинг (2017) - Великобритания
51. Мотылёк (2017) - США
52. Выстрел в пустоту (2015) - США
53. Приключения Паддингтона 2 (2017) - Франция
54. Ученик чудовища (2015) - Япония
55. Мстители: Война бесконечности (2018) - США
56. Мстители: Финал (2019) - США
57. Ла-Ла Ленд (2016) - США
58. Экипаж (2016) - Россия
59. Ford против Ferrari (2019) - США
60. Дурак (2014) - Россия
61. Пеле: Рождение легенды (2015) - США
62. Чудо (2017) - США
63. Хоббит: Битва пяти воинств (2014) - Новая Зеландия
64. Исчезнувшая (2014) - США
65. Отель «Гранд Будапешт» (2014) - США
66. Лучшее предложение (2012) - Италия
67. По соображениям совести (2016) - США
68. Охота (2012) - Дания
69. Лекарь: Ученик Авиценны (2013) - Германия
70. Игра в имитацию (2014) - США
71. 12 лет рабства (2013) - Великобритания
72. Легенда №17 (2012) - Россия
73. Бегущий по лезвию 2049 (2017) - США
74. Джанго освобожденный (2012) - США
75. Деревья на асфальте (1984) - СССР
76. 1+1 (2011) - Франция
77. Невозможное (2012) - Испания
78. Выживший (2015) - США
79. С любовью, Рози (2014) - Великобритания
80. Иллюзия обмана (2013) - США
81. Век Адалин (2015) - США
82. Один день (2011) - США
83. Король говорит! (2010) - США
84. Убойные каникулы (2010) - Канада
85. Прислуга (2011) - США
86. О чём говорят мужчины (2010) - Россия
87. Области тьмы (2011) - США
88. Волк с Уолл-стрит (2013) - США
89. Пленницы (2013) - США
90. Начало (2010) - США
91. Воин (2011) - США
92. Темный рыцарь: Возрождение лег (2012) - США
93. Пожары (2010) - Канада
94. Миллионер из трущоб (2008) - Великобритания
95. Гарри Поттер и Дары Смерти: Ча (2011) - Великобритания
96. Законопослушный гражданин (2009) - США
97. Остров проклятых (2009) - США
98. Хатико: Самый верный друг (2008) - США
99. Шерлок Холмс и доктор Ватсон:  (1980) - СССР
100. Хоббит: Нежданное путешествие (2012) - Новая Зеландия
101. Марли и я (2008) - США
102. Интерстеллар (2014) - США
103. Аватар (2009) - США
104. Нефть (2007) - США
105. Престиж (2006) - Великобритания
106. Старикам тут не место (2007) - США
107. Апокалипсис (2006) - США
108. Темный рыцарь (2008) - США
109. Дьявол носит Prada (2006) - США
110. В погоне за счастьем (2006) - США
111. Пираты Карибского моря: На кра (2007) - США
112. Иллюзионист (2005) - США
113. Бесподобный мистер Фокс (2009) - США
114. Освобождение: Огненная дуга (1968) - СССР
115. Гарри Поттер и Принц-полукровк (2009) - Великобритания
116. Счастливое число Слевина (2005) - США
117. Алеша Попович и Тугарин Змей (2004) - Россия
118. Отступники (2006) - США
119. Малышка на миллион (2004) - США
120. Загадочная история Бенджамина  (2008) - США
121. Самый быстрый Indian (2005) - Новая Зеландия
122. Собачье сердце (1988) - СССР
123. Покровские ворота (1982) - СССР
124. Олдбой (2003) - Корея Южная
125. Пираты Карибского моря: Сундук (2006) - США
126. Укрощение строптивого (1980) - Италия
127. Железный человек (2008) - США
128. Игрушка (1976) - Франция
129. Хористы (2004) - Франция
130. Кин-дза-дза! (1986) - СССР
131. Бриллиантовая рука (1968) - СССР
132. На войне как на войне (1968) - СССР
133. Убить Билла 2 (2004) - США
134. Мимино (1977) - СССР
135. 12 стульев (1971) - СССР
136. Не может быть! (1975) - СССР
137. Три плюс два (1963) - СССР
138. Белое солнце пустыни (1969) - СССР
139. Берегись автомобиля (1966) - СССР
140. Вокзал для двоих (1982) - СССР
141. Белорусский вокзал (1970) - СССР
142. Девчата (1961) - СССР
143. Кавказская пленница, или Новые (1966) - СССР
144. Вам и не снилось... (1980) - СССР
145. Десять негритят (1987) - СССР
146. Калина красная (1973) - СССР
147. Курьер (1986) - СССР
148. Жестокий романс (1984) - СССР
149. Самая обаятельная и привлекате (1985) - СССР
150. Сталкер (1979) - СССР
151. Судьба человека (1959) - СССР
152. Гараж (1979) - СССР
153. Свой среди чужих, чужой среди  (1974) - СССР
154. Афоня (1975) - СССР
155. Иди и смотри (1985) - СССР
156. Операция «Ы» и другие приключе (1965) - СССР
157. Брат 2 (2000) - Россия
158. Ворошиловский стрелок (1999) - Россия
159. В августе 44-го (2001) - Россия
160. Война (2002) - Россия
161. Брат (1997) - Россия
162. Достучаться до небес (1997) - Германия
163. Такси (1998) - Франция
164. Васаби (2001) - Франция
165. Игра (1997) - США
166. Гарри Поттер и Кубок огня (2005) - Великобритания
167. Акира (1987) - Япония
168. Нечто (1982) - США
169. Один дома (1990) - США
170. Призрак в доспехах (1995) - Япония
171. Летят журавли (1957) - СССР
172. Бронкская история (1993) - США
173. Особенности национальной охоты (1995) - Россия
174. Холодное лето пятьдесят третье (1987) - СССР
175. Гнев (2004) - США
176. Догвилль (2003) - Дания
177. Звёздные войны: Эпизод 3 – Мес (2005) - США
178. Вечное сияние чистого разума (2004) - США
179. Назад в будущее 2 (1989) - США
180. Шрэк 2 (2004) - США
181. Эффект бабочки (2003) - США
182. Лицо со шрамом (1983) - США
183. Шоу Трумана (1998) - США
184. Общество мертвых поэтов (1989) - США
185. Пираты Карибского моря: Прокля (2003) - США
186. Рэмбо: Первая кровь (1982) - США
187. Троя (2004) - США
188. Властелин колец: Возвращение к (2003) - Новая Зеландия
189. Константин: Повелитель тьмы (2005) - США
190. Страсти Христовы (2004) - США
191. Адвокат дьявола (1997) - США
192. Трасса 60 (2001) - Канада
193. Дневник памяти (2004) - США
194. Пятый элемент (1997) - Франция
195. Убить Билла (2003) - США
196. Казино (1995) - США
197. Титаник (1997) - США
198. Люди в чёрном (1997) - США
199. Чего хотят женщины (2000) - США
200. Такси 2 (2000) - Франция
201. Человек-паук (2002) - США
202. Лило и Стич (2002) - США
203. Жизнь Дэвида Гейла (2002) - Великобритания
204. Планета Ка-Пэкс (2001) - Германия
205. Гарри Поттер и философский кам (2001) - Великобритания
206. Гарри Поттер и Тайная комната (2002) - Великобритания
207. Семьянин (2000) - США
208. Изгой (2000) - США
209. Схватка (1995) - США
210. Умница Уилл Хантинг (1997) - США
211. Игры разума (2001) - США
212. Большой куш (2000) - Великобритания
213. День сурка (1993) - США
214. Карты, деньги, два ствола (1998) - Великобритания
215. Терминатор (1984) - США
216. Римские каникулы (1953) - США
217. Гладиатор (2000) - США
218. Назад в будущее (1985) - США
219. Унесённые ветром (1939) - США
220. Терминатор 2: Судный день (1991) - США
221. Принцесса Мононоке (1997) - Япония
222. Форрест Гамп (1994) - США
223. Шрэк (2001) - США
224. Зеленая миля (1999) - США
225. Чужие (1986) - Великобритания
226. Храброе сердце (1995) - США
227. Леон (1994) - Франция
228. Шестое чувство (1999) - США
229. Бешеные псы (1991) - США
230. Чужой (1979) - Великобритания
231. Американская история X (1998) - США
232. Унесённые призраками (2001) - Япония
233. Семь (1995) - США
234. Спасти рядового Райана (1998) - США
235. Бойцовский клуб (1999) - США
236. Реквием по мечте (2000) - США
237. Славные парни (1990) - США
238. Пианист (2002) - Франция
239. Красота по-американски (1999) - США
240. Молчание ягнят (1990) - США
241. Амели (2001) - Франция
242. Криминальное чтиво (1994) - США
243. 12 разгневанных мужчин (1956) - США
244. Мементо (2000) - США
245. Пролетая над гнездом кукушки (1975) - США
246. Список Шиндлера (1993) - США
247. Властелин колец: Братство коль (2001) - Новая Зеландия
248. Крестный отец (1972) - США
249. Гарри Поттер и узник Азкабана (2004) - Великобритания
250. Поймай меня, если сможешь (2002) - США

Собрано 250 фильмов из 250

In [162]:
df_new.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250 entries, 0 to 249
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   title        250 non-null    object
 1   year         250 non-null    int64
 2   country      250 non-null    object
 3   rating       250 non-null    object
 4   description  250 non-null    object
dtypes: int64(1), object(4)
memory usage: 9.9+ KB

In [163]:
df_new.head(10)

,title,year,country,rating,description
0,Батя,2020,Россия,7.9,История о путешествии взрослого героя к своему...
1,Крик тишины,2019,Россия,8.6,"Блокадный Ленинград, февраль 1942 года. Заканч..."
2,Темные воды,2019,США,7.9,Адвокат Роберт Билотт выступает с обвинением в...
3,Уроки фарси,2020,Россия,8.0,"1942 год, оккупированная Европа. Оказавшись в ..."
4,Подольские курсанты,2020,Россия,8.4,"Октябрь 1941 года, Подмосковье. Около трёх с п..."
5,Достать ножи,2019,США,8.2,На следующее утро после празднования 85-летия ...
6,Огонь,2020,Россия,8.1,После гибели подчинённого бывалый инструктор б...
7,Дело Коллини,2019,Германия,8.0,"Берлин, 2001 год. Молодой адвокат Каспар Лайне..."
8,Джентльмены,2019,США,8.7,Один ушлый американец ещё со студенческих лет ...
9,Пальма,2020,Россия,8.4,Овчарка по кличке Пальма вынужденно расстается...

### Объединение фильмов в 1 файл

In [164]:
file_name = 'top250.csv'

try:
    df_existing = pd.read_csv(file_name, encoding='utf-8-sig')
    df_combined = pd.concat([df_existing, df_new], ignore_index=True)
    df_combined.to_csv(file_name, index=False, encoding='utf-8-sig')
    print(f"Данные добавлены. Было: {len(df_existing)}, стало: {len(df_combined)}")
except FileNotFoundError:
    df_new.to_csv(file_name, index=False, encoding='utf-8-sig')
    print(f"Создан новый файл '{file_name}' с {len(df_new)} фильмами")

Данные добавлены. Было: 250, стало: 500

### Удаление дубликатов

In [165]:
file_name = 'top250.csv'
new_file_name = 'top250_no_duplicates.csv'

df = pd.read_csv(file_name, encoding='utf-8-sig')
print(f"Было: {len(df)}")

duplicates = df[df.duplicated(subset=['title', 'year', 'country'], keep=False)]

if len(duplicates) > 0:
    print(f"Найдено дубликатов: {len(duplicates)}")
    print("\nВсе дублирующиеся записи:")
    print(duplicates[['title', 'year', 'country', 'rating']].to_string(index=False))
    
    # Удаляем дубликаты
    df_cleaned = df.drop_duplicates(subset=['title', 'year', 'country'])
    print(f"\nСтало: {len(df_cleaned)}")
    
    df_cleaned.to_csv(new_file_name, index=False, encoding='utf-8-sig')
    print(f"Создан файл: {new_file_name}")
else:
    print("Дубликатов не найдено")

Было: 500
Найдено дубликатов: 100

Все дублирующиеся записи:
                        title  year        country  rating
                Крестный отец  1972            США     9.2
                Темный рыцарь  2008            США     9.1
              Список Шиндлера  1993            США     9.0
           Криминальное чтиво  1994            США     8.8
                 Форрест Гамп  1994            США     8.8
                Славные парни  1990            США     8.7
 Пролетая над гнездом кукушки  1975            США     8.6
                         Семь  1995            США     8.6
       Спасти рядового Райана  1998            США     8.6
                 Зеленая миля  1999            США     8.6
              Назад в будущее  1985            США     8.5
                   Отступники  2006            США     8.5
                         Леон  1994        Франция     8.5
                          1+1  2011        Франция     8.5
         Джанго освобожденный  2012            США     8.5
Мстители: Война бесконечности  2018            США     8.4
          Умница Уилл Хантинг  1997            США     8.4
              Мстители: Финал  2019            США     8.4
                   Тайна Коко  2017            США     8.4
               Храброе сердце  1995            США     8.3
           Принцесса Мононоке  1997         Япония     8.3
       Красота по-американски  1999            США     8.3
                       Джокер  2019            США     8.3
                 Иди и смотри  1985           СССР     8.3
             Реквием по мечте  2000            США     8.3
                        Охота  2012          Дания     8.3
                       Пожары  2010         Канада     8.3
 Вечное сияние чистого разума  2004            США     8.3
                      Схватка  1995            США     8.3
               Лицо со шрамом  1983            США     8.3
            Волк с Уолл-стрит  2013            США     8.2
                  Шоу Трумана  1998            США     8.2
                  Оппенгеймер  2023            США     8.2
                Зеленая книга  2018            США     8.2
             Остров проклятых  2009            США     8.2
                        Нефть  2007            США     8.2
               Шестое чувство  1999            США     8.2
        Старикам тут не место  2007            США     8.2
                        Нечто  1982            США     8.2
                     Пленницы  2013            США     8.2
                  Убить Билла  2003            США     8.2
                  Игры разума  2001            США     8.2
    Карты, деньги, два ствола  1998 Великобритания     8.1
    Поймай меня, если сможешь  2002            США     8.1
      Общество мертвых поэтов  1989            США     8.1
                  Дикий робот  2024            США     8.2
                         Воин  2011            США     8.1
           Малышка на миллион  2004            США     8.1
      По соображениям совести  2016            США     8.1
                  Исчезнувшая  2014            США     8.1
                Зеленая книга  2018            США     8.5
                   Тайна Коко  2017            США     8.7
                  Дикий робот  2024            США     8.4
                  Оппенгеймер  2023            США     8.1
                       Джокер  2019            США     8.0
Мстители: Война бесконечности  2018            США     8.1
              Мстители: Финал  2019            США     7.9
                  Исчезнувшая  2014            США     8.0
      По соображениям совести  2016            США     8.2
                        Охота  2012          Дания     7.9
         Джанго освобожденный  2012            США     8.3
                          1+1  2011        Франция     8.9
            Волк с Уолл-стрит  2013            США     8.1
                     Пленницы  2013            США     7.8
                         Воин  2011            США     8.1
                       Пожары  2010         Канада     8.1
             Остров проклятых  2009            США     8.6
                        Нефть  2007            США     7.9
        Старикам тут не место  2007            США     7.8
                Темный рыцарь  2008            США     8.5
                   Отступники  2006            США     8.5
           Малышка на миллион  2004            США     8.2
                 Иди и смотри  1985           СССР     8.3
                        Нечто  1982            США     7.9
 Вечное сияние чистого разума  2004            США     8.0
               Лицо со шрамом  1983            США     8.2
                  Шоу Трумана  1998            США     8.3
      Общество мертвых поэтов  1989            США     8.3
                  Убить Билла  2003            США     7.7
                      Схватка  1995            США     8.1
          Умница Уилл Хантинг  1997            США     8.1
                  Игры разума  2001            США     8.5
    Карты, деньги, два ствола  1998 Великобритания     8.6
              Назад в будущее  1985            США     8.6
           Принцесса Мононоке  1997         Япония     8.3
                 Форрест Гамп  1994            США     8.9
                 Зеленая миля  1999            США     9.1
               Храброе сердце  1995            США     8.3
                         Леон  1994        Франция     8.7
               Шестое чувство  1999            США     8.2
                         Семь  1995            США     8.3
       Спасти рядового Райана  1998            США     8.2
             Реквием по мечте  2000            США     8.0
                Славные парни  1990            США     8.1
       Красота по-американски  1999            США     8.0
           Криминальное чтиво  1994            США     8.7
 Пролетая над гнездом кукушки  1975            США     8.5
              Список Шиндлера  1993            США     8.9
                Крестный отец  1972            США     8.7
    Поймай меня, если сможешь  2002            США     8.5

Стало: 450
Создан файл: top250_no_duplicates.csv

### Просмотр общей информации о сохраненных данных

In [166]:
df_cleaned = pd.read_csv(new_file_name, encoding='utf-8-sig')
df_cleaned.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 450 entries, 0 to 449
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   title        450 non-null    object
 1   rating       450 non-null    float64
 2   year         450 non-null    int64
 3   country      445 non-null    object
 4   description  444 non-null    object
dtypes: float64(1), int64(1), object(3)
memory usage: 17.7+ KB

In [167]:
df.head(10)

,title,rating,year,country,description
0,Побег из Шоушенка,9.3,1994,США,Успешный банковский служащий Энди Дюфрейн осуж...
1,Крестный отец,9.2,1972,США,В центре культовой криминальной драмы Фрэнсиса...
2,Темный рыцарь,9.1,2008,США,Действие фильма начинается с ограбления Готэмс...
3,Крестный отец 2,9.0,1974,США,Молодой Вито теряет семью из-за преследования ...
4,12 разгневанных мужчин,9.0,1957,США,"Классика кинематографа 1950-х, выросшего из те..."
5,Властелин Колец: Возвращение Короля,9.0,2003,США / Новая Зеландия / Германия,Битва за Средиземье продолжается. Хоббиты и их...
6,Список Шиндлера,9.0,1993,США,"Начало Второй мировой войны. После того, как П..."
7,Властелин Колец: Братство Кольца,8.9,2001,Новая Зеландия / США,"Средиземье — континент, населенный разными и о..."
8,Криминальное чтиво,8.8,1994,США,Джулс Уиннфилд и Винсент Вега – парочка киллер...
9,"Хороший, плохой, злой",8.8,1966,Италия / Испания / Германия,В разгар гражданской войны таинственный стрело...